const student = {
  id: undefined,
  documentType: undefined,
  document: '',
  name: '',
  surname: '',
  gender: undefined,
  birthDate: undefined,
  nationality: '',
  civilState: undefined,
  email: '',
  telephone: '',
  cellphone: '',
  educationStateFather: '',
  educationStateMother: '',
  state: undefined,
  department: undefined,
  street: '',
  doorNumber: '',
  floor: '',
  block: '',
  zipCode: '',
  terms: false,
  personalPhoto: undefined,
  documentPhoto: undefined,
  certificatePhoto: undefined,
  approvedMattersPhoto: undefined,
};

export default { student };
