export default [
  { value: '02', label: 'CABA' },
  { value: '06', label: 'Buenos Aires' },
  { value: '10', label: 'Catamarca' },
  { value: '14', label: 'Córdoba' },
  { value: '18', label: 'Corrientes' },
  { value: '22', label: 'Chaco' },
  { value: '26', label: 'Chubut' },
  { value: '30', label: 'Entre Ríos' },
  { value: '34', label: 'Formosa' },
  { value: '38', label: 'Jujuy' },
  { value: '42', label: 'La Pampa' },
  { value: '46', label: 'La Rioja' },
  { value: '50', label: 'Mendoza' },
  { value: '54', label: 'Misiones' },
  { value: '58', label: 'Neuquén' },
  { value: '62', label: 'Río Negro' },
  { value: '66', label: 'Salta' },
  { value: '70', label: 'San Juan' },
  { value: '74', label: 'San Luis' },
  { value: '78', label: 'Santa Cruz' },
  { value: '82', label: 'Santa Fe' },
  { value: '86', label: 'Santiago del Estero' },
  { value: '90', label: 'Tucumán' },
  { value: '94', label: 'Tierra del Fuego' },
];
