const PREFIX = 'Auth/';

export const GET_LOGIN_REQUEST = `${PREFIX}GET_LOGIN_REQUEST`;
export const GET_LOGIN_SUCCESS = `${PREFIX}GET_LOGIN_SUCCESS`;
export const GET_LOGIN_ERROR = `${PREFIX}GET_LOGIN_ERROR`;

export const GET_TOKEN_REQUEST = `${PREFIX}GET_TOKEN_REQUEST`;
export const GET_TOKEN_SUCCESS = `${PREFIX}GET_TOKEN_SUCCESS`;
export const REMOVE_TOKEN = `${PREFIX}REMOVE_TOKEN`;
